# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hasker', '0004_auto_20170901_0113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='value',
            new_name='is_positive',
        ),
    ]
