# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasker', '0005_auto_20170901_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_filename',
            field=models.TextField(null=True, unique=True),
        ),
    ]
