# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasker', '0006_auto_20170901_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
