# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasker', '0007_auto_20170901_0222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='is_positive',
        ),
        migrations.AddField(
            model_name='vote',
            name='value',
            field=models.SmallIntegerField(choices=[(1, b'Positive'), (-1, b'Negative')])
        ),
    ]
