# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 06:10
from __future__ import unicode_literals

from django.db import migrations, models
import hasker.models


class Migration(migrations.Migration):

    dependencies = [
        ('hasker', '0008_auto_20170901_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar_filename',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_file',
            field=models.FileField(upload_to=hasker.models._get_file_path),
        ),
    ]
