# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 07:20
from __future__ import unicode_literals

from django.db import migrations, models
import hasker.models


class Migration(migrations.Migration):

    dependencies = [
        ('hasker', '0009_auto_20170901_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar_file',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to=hasker.models._get_file_path)
        ),
    ]
