# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 16:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hasker', '0012_auto_20170903_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(choices=[(1, b'Positive'), (-1, b'Negative')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='voteforanswer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='voteforanswer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='voteforquestion',
            name='question',
        ),
        migrations.RemoveField(
            model_name='voteforquestion',
            name='user',
        ),
        migrations.DeleteModel(
            name='VoteForAnswer',
        ),
        migrations.DeleteModel(
            name='VoteForQuestion',
        ),
        migrations.AddField(
            model_name='answer',
            name='votes',
            field=models.ManyToManyField(to='hasker.Vote'),
        ),
        migrations.AddField(
            model_name='question',
            name='votes',
            field=models.ManyToManyField(to='hasker.Vote'),
        ),
    ]
